In [ ]:
print("hello")

hello


In [ ]:
!nvidia-smi

Sat Feb 17 05:15:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch

print(torch.__version__)

2.1.0+cu121


Creating tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6522, 0.4492, 0.9326, 0.3658],
        [0.0503, 0.5528, 0.1340, 0.3091],
        [0.5643, 0.5673, 0.6883, 0.9963]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8322, 0.6838, 0.6383, 0.9544],
        [0.7248, 0.6174, 0.5218, 0.5803],
        [0.2664, 0.4238, 0.4526, 0.6961]])

In [ ]:
some_tensor.dtype

torch.float32

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
some_tensor.device

device(type='cpu')

Manipulating tensors

In [2]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [3]:
tensor * 10

tensor([10, 20, 30])

In [4]:
tensor - 10

tensor([-9, -8, -7])

In [5]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [6]:
torch.add(tensor, 10)

tensor([11, 12, 13])

Matrix multiplication

In [7]:
tensor * tensor

tensor([1, 4, 9])

In [8]:
torch.matmul(tensor, tensor)

tensor(14)

Reshaping, stacking, squeezing and unsqueezing tensors

In [9]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [11]:
y = x.view(9, 1)
y, y.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [12]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [16]:
y[:, 0] = 4
y, x

(tensor([[4.],
         [4.],
         [4.],
         [4.],
         [4.],
         [4.],
         [4.],
         [4.],
         [4.]]),
 tensor([4., 4., 4., 4., 4., 4., 4., 4., 4.]))

In [17]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [18]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
x.shape

torch.Size([9])

In [21]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
x_reshaped.squeeze().shape

torch.Size([9])

In [24]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [27]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])